import arcade

SPRITE_SCALING = 0.5
ENEMY_SCALING = 0.25
NPC_SCALING = 0.8
HEART_SCALING = 0.3
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)

TALK_DISTANCE = 150

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = "Mohg Quest"

MOVEMENT_SPEED = 8